### ISSUE TITLE
How to POST a JSON record in HTTP body?

### ISSUE THREAD

**Issue by benpate** [BrandonRomano/wrecker#11]
I see how to POST form data using x-www-form-urlencoded, but how do you set the entire request body to a value (such as a JSON encoded record?)

**Comment by BrandonRomano** [comment]
@benpate There's currently not a way to do this.  It should be pretty easy to add it into the library, so if you'd like you can take a stab at it -- if not I can add this to my list of things to do!

**Comment by benpate** [comment]
Sure.  I'll take a shot.  I don't want to mess up your flow, so please tell me if my idea fits into your overall design.

I'll probably add a WithBody() function along with corresponding data in the wrecker.WreckerRequest data structure.  If that's OK with you, then I'll make a pull request here in a bit.

**Comment by benpate** [comment]
One more thought.  The r.WreckerClient.sendRequest() funciton is going to get really verbose if I keep adding parameters to it (like Headers and Body).  

Unless you'd prefer otherwise, my pull request will simplify this by passing the whole Request object through to the Client.  That way, all of the data is available to us when we need.  It might also save us a little memory by passing pointers instead of concatenated strings (which are pass by value)

Does this work for you?

**Comment by BrandonRomano** [comment]
Yup, I think that would be the general way I would have went about it..

I was just about to suggest your second suggestion -- so yes you can include that in the PR!

**Comment by benpate** [comment]
word.

**Comment by BrandonRomano** [comment]
:fist:

**Comment by BrandonRomano** [comment]
Whoops
