### ISSUE TITLE
Split Params into separate structures for URL params and Form params

### ISSUE THREAD

**Issue by BrandonRomano** [BrandonRomano/wrecker#17]
- [ ] Add `WithUrlParam`
- [ ] Add `WithFormParam`
- [ ] Remove the old `WithParam`
- [ ] Update tests
- [ ] Update the README

Ref #13

**Comment by benpate** [comment]
Since we are shortening the function names, it seems like I should at least use "URLParam" and "FormParam". But, do you think it would be too much to shorten it to simply URL and Form?

**Comment by BrandonRomano** [comment]
Hmm, I think that would actually get a little confusing.  `URL` could mean the URL of the request, and `Form` could be misinterpreted to be the entire form.

I'm thinking we should stick with `URLParam` + `FormParam` for now, but perhaps at a later date we can provide shorter aliases for all these functions?

**Comment by benpate** [comment]
Good point.  That’s the right way to go.

—
Ben

**Comment by benpate** [comment]
This is fixed by PR #25
