### ISSUE TITLE
Add WithHeader method

### ISSUE THREAD

**Issue by BrandonRomano** [BrandonRomano/wrecker#5]
Add a `WithHeader` function that will add headers to a request  (Key -> Value).

**Comment by benpate** [comment]
Please see Pull Request #6.  Does this add WithHeader() correctly?

**Comment by benpate** [comment]
I think this one is resolved.  Feel free to reopen if I'm jumping the gun.

**Comment by BrandonRomano** [comment]
Oh yeah this is resolved.  Usually you can write in the PR that resolves an issue `Fixes #5` (or whatever number the issue you're resolving) and it will automatically close this issue.

You're correct in closing this.. Thanks!
