### ISSUE TITLE
Improve Error Handling

### ISSUE THREAD

**Issue by benpate** [BrandonRomano/wrecker#7]
Do you have any specific plans for handling HTTP errors?

Different REST APIs will have different return formats (JSON, Text, etc) -- but there should be some way to return some error information that is common to all APIs.  For instance, you could return the HTTP status code along with the body text for additional parsing.

**Comment by BrandonRomano** [comment]
Hey @benpate.  I actually plan on exposing the entire [http.Response](http://golang.org/pkg/net/http/#Response).  I don't know why I'm actually not returning that already, so I'll work on this soon!
